### ISSUE TITLE
Should have support for AVRO data in Sink

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#12]
Should be able to receive messages from a Kafka topic in avro, and write to Cosmos DB as simple JSON.

**Comment by ryancrawcour** [comment]
**Configuration example for AVRO**
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081

value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

**Comment by saggarsunil** [comment]
Do we have this support now ?  We want to write the data coming from kafka-topic(avro) to cosmosdb

**Comment by ryancrawcour** [comment]
thanks for reaching out. agree that avro support would be good to have. don't have a timeline to add this. but we can prioritize this if it's a blocker for customers.

**Comment by saggarsunil** [comment]
It is a blocker for us now. Since we are stretched on time, we have starting adding support in application to directly push the data to cosmosdb (instead of going through topic), which is a bad design approach.

**Comment by ryancrawcour** [comment]
thanks @saggarsunil will look in to this shortly and provide and estimate.

**Comment by ryancrawcour** [comment]
at this stage, are you only looking for Sink support for avro, or would you want this in the Source connector too? just checking so i know which to prioritize.

**Comment by ryancrawcour** [comment]
@saggarsunil could you also please answer the following questions for me regarding the implementation - 

- assume you will have an external schema registry that will store the schema for the avro file, or will the schema be included in the avro file itself? 
- what should the Sink Connector do if it fails to find the schema? 
- what should the Sink Connector do if the body of the message fails schema validation? 
- how should types be mapped from avro where JSON has no corresponding type, such as DateTime?

**Comment by saggarsunil** [comment]
Currentl we are interesting in sink connector only.

Answers to your questions
Q. Assume you will have an external schema registry that will store the schema for the avro file, or will the schema be included in the avro file itself?
--> External schema registry
Q. what should the Sink Connector do if it fails to find the schema?
--> It should throw a schema not found exception
Q. what should the Sink Connector do if the body of the message fails schema validation?
--> Schema validation exception 
Q. how should types be mapped from avro where JSON has no corresponding type, such as DateTime? 
long

**Comment by ryancrawcour** [comment]
related to #14
