### ISSUE TITLE
Sink should support TTL

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#139]
**## Problem Statement**
Cosmos DB supports Time to Live (TTL). This TTL can be configured at a collection level, and overridden on an individual document level. 

Documents being written to Cosmos DB by the Sink connector should support setting of a custom TTL property on a document.

**## Proposed Solution**
Add an additional configuration parameter to set the TTL to use when writing any new documents to Cosmos DB

## Next Steps
- [x] Team consensus to proceed 
- [ ] Complete Design Review
- [ ] Schedule Design Session

**Comment by ryancrawcour** [comment]
This can probably be done fairly easily using an InsertField SMT, inserting a static field in to the message as it flows from Kafka before it hits Cosmos DB

**Comment by sivamu** [comment]
I'm wondering if in addition to the field, we would need to configure the database/container to enforce the TTL. This is in reference to here:
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2%2Cjavav4#set-time-to-live-on-an-item

**Comment by ryancrawcour** [comment]
this is a good point. it won't fail if the container doesn't have ttl set on it, it will just be ignored. 
the user can then go enable ttl themselves on the container and it will then get picked up and dealt with. 

i am reluctant to go modify the container, because setting ttl at the container sets a default ttl for that container, which you can then override per document. but all the documents already in the container now get a default ttl. and any document newly inserted in to the container gets a default ttl. so if we did enable the ttl on the container we'd have to set it to 0 (which afaik means infinite).

**Comment by ryancrawcour** [comment]
i am wondering if we just leave this to be done with an SMT and not even both with adding code for this?

**Comment by sivamu** [comment]
If it works with the SMT only, I am in favor of that approach. I've looked into adding the code and it's pretty tricky.

**Comment by ryancrawcour** [comment]
it should work with a simple InsertField SMT. you can then choose to setup a static value, and have all messages being inserted from this connector have a static TTL value. 

it should be easy to setup and test this. 
if you only want some documents coming from this connector to have TTL and others not, then adding in a Predicate to the SMT should also work. 

wanna setup a test in the (integration) tests project to verify this? 
if it works we can close this as #wontfix

**Comment by sivamu** [comment]
Will add the Integration test in #205. Closing this issue.
