### ISSUE TITLE
Documentation for Source connector

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#156]
Complete documentation README for Source connector - 

Getting started (full tutorial like walkthrough)
Installation (document how to download and install and configure connector)
Config options (document each config option)

**Comment by Adama94** [comment]
Would just like to +1 the need for documentation here. I'm a user looking to get this running and there is little documentation, especially around how to use, installation instructions, etc. So little in fact I'm not even sure this is an actively maintained repository.

**Comment by ryancrawcour** [comment]
it is an active maintained repo. we have been quite light on documentation to date, but we're busy addressing that now. 
if there's anything specifically you'd like to see in the doc please let us know here and we'll be sure to address them. 
for now, 

check out the current [Source Connector Docs](https://github.com/microsoft/kafka-connect-cosmosdb/blob/dev/doc/README_Source.md)  and let us know how we can improve on this.

**Comment by Adama94** [comment]
I think starting with up to date documentation on how to build the repo would be a good place. For example, I downloaded maven and a clean version of this repo and run into errors running `mvn clean package`. 

![image](https://user-images.githubusercontent.com/4806883/100684509-55268780-332f-11eb-8e30-57e767c08a06.png)

**Comment by ryancrawcour** [comment]
shortly we will be publishing a beta-1 release here on github, so if you just need the JAR it will be available for download and you won't need to build the jar yourself.

**Comment by Adama94** [comment]
Also I'm sure this isn't the right venue for this, but is this expected to work with other managed Kafka instances, or is this limited to Event Hub?

**Comment by Adama94** [comment]
Yes I just need the JAR to test to see if this works for my use case. If you have a working version of the JAR I can download from somewhere let me know.

**Comment by ryancrawcour** [comment]
however, i would like to know what errors you run in to, because we need to make sure that we address this in the developer-walkthrough documentation we're currently working on.

**Comment by ryancrawcour** [comment]
> Also I'm sure this isn't the right venue for this, but is this expected to work with other managed Kafka instances, or is this limited to Event Hub?

this should work with any instance of Kafka, whether that is self-hosted, on Azure HDI, EventHubs with Kafka, and hopefully one day in the future with the fully managed Confluent Cloud on Azure.

**Comment by ryancrawcour** [comment]
> Yes I just need the JAR to test to see if this works for my use case. If you have a working version of the JAR I can download from somewhere let me know.

i will publish a release to github in a day or two. 
also, happy to jump on a Teams/Zoom/Skype call with you and discuss your scenario further if you like.

**Comment by Adama94** [comment]
Here is text dump of the errors, they seem related to Mockito, but it fails to produce the JAR file. 

[mvn_clean_package.txt](https://github.com/microsoft/kafka-connect-cosmosdb/files/5619664/mvn_clean_package.txt)

**Comment by Adama94** [comment]
We have a fully managed Confluent Cloud Kafka instance at the moment, it sounds like this connector won't support this at the moment, is that right? If so, I'll need to look into other options.

**Comment by ryancrawcour** [comment]
thanks for the logs. yes, it appears the tests are failing now due to Mockito trying to mock to the latest Cosmos client

**Mockito cannot mock this class: class com.azure.cosmos.CosmosAsyncClient.**
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

I will open a new bug to address this. Thanks.

**Comment by ryancrawcour** [comment]
Bug #169  opened to address this.

**Comment by ryancrawcour** [comment]
> We have a fully managed Confluent Cloud Kafka instance at the moment, it sounds like this connector won't support this at the moment, is that right? If so, I'll need to look into other options.

right now, it won't, no. it will only work with a self-managed Kafka Connect, **however**, we just met with Confluent today and the process to get this connector certified and supported in a fully-managed environment like Confluent Cloud has begun. approx ETA is early next year. 

if you would like to know about this, please ping me (name dot surname at company name dot com) and we can chat further offline about this.

**Comment by ryancrawcour** [comment]
when documenting Source & Sink connector let's ensure we refer to the Confluent docs for Connect config - 
https://docs.confluent.io/platform/current/connect/references/allconfigs.html#

and that we call out the most useful config options, things like key.converter, value.converter, offset.flush.interval.ms, offset.flush.timeout.ms, and other config related to [Distributed Worker Configuration](https://docs.confluent.io/platform/current/connect/references/allconfigs.html#distributed-worker-configuration) like offset.storage.topic and

**Comment by ryancrawcour** [comment]
> Yes I just need the JAR to test to see if this works for my use case. If you have a working version of the JAR I can download from somewhere let me know

@Adama94 i just pushed [v1.0.0-beta](https://github.com/microsoft/kafka-connect-cosmosdb/releases/tag/v1.0.0-beta). Please test this and let me know.

**Comment by ryancrawcour** [comment]
> Here is text dump of the errors, they seem related to Mockito, but it fails to produce the JAR file.
> [mvn_clean_package.txt](https://github.com/microsoft/kafka-connect-cosmosdb/files/5619664/mvn_clean_package.txt)

@Adama94 we've opened #169 to track the issues you were having on building the jar. 
Thus far we're unable to repro this.
Could we please continue the discussion in #169 so that we can try dig in to this further and see why "it works on my machine". We must have something setup differently somewhere.

**Comment by ryancrawcour** [comment]
Consider adding a section in to Source documentation that demonstrates using a SMT to remove all Cosmos DB system properties when reading the document from the ChangeFeed and before writing to Kafka.
