### ISSUE TITLE
Source Connectors changes might get lost if interrupted

### ISSUE THREAD

**Issue by marcelopio** [microsoft/kafka-connect-cosmosdb#166]
According to code:
https://github.com/microsoft/kafka-connect-cosmosdb/blob/87c81fa2a21c5537cd8975c7243cc38dfd1a1216/src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java#L93

The problem is that, if there is some interruption after the changes are polled they could be lost. 

My suggestion is to use kafka offsets so we can guarantee and poll from kafka the latest change that it acquired.

**Comment by ryancrawcour** [comment]
the problem we have is that offsets are now maintained in 2 places. 
cosmos db - to set where to start reading the change feed fro
kafka - to set where the connector got to when writing to kafka

as you know in cosmos we can set the start datetime, or give it a continuation token, or start from current datetime, or from the beginning. none of these easily map across to a kafka offest. 

i agree that currently we have a potential mismatch and the scope for loss. 
will need to investigate the best way to handle this.

**Comment by brandynbrown** [comment]
@ryancrawcour can you investigate this week and remove label when you feel it's ready for pickup?

**Comment by marcelopio** [comment]
I was searching for a solution for this problem, and Debezium has a solution that they use in some connectors, that is to write to the database after they send the poll batch. This could be a solution, and at the start of the connector, look for a mismatch between the current lease and the lease that we custom wrote, if there is a mismatch, rewind the lease to the last written.

A problem that I still see is that there is a probability to duplicate data. But if we start to send the key, solving issue #159, it should be ok.

**Comment by ryancrawcour** [comment]
I notice the MongoDB Source connector uses a Kafka topic to maintain offset information - 

![image](https://user-images.githubusercontent.com/38923605/102284050-6959be00-3f98-11eb-973d-6177093bebb4.png)
