### ISSUE TITLE
Have to delete and reconfigure connector every time there is an error

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#175]
## Description
Every time there is an error while the connector is running it goes in to a failed state. 
To get it out of a failed state you have to completely delete the configured connector and reconfigure it again. 

## Expected Behavior
Should be able to fix error "either by fixing the data in Kafka/Cosmos, or by fixing the configuration, then resume the connector and have it attempt to restart itself,

## Reproduce
Configure sink connector, with invalid databasename
Produce message
Wait for connector to fail due to configuration
Correct the configuration
Try to restart the connector

## Additional Context 
For additional context on how connectors should handle exceptions refer to [Deep Dive Error Handling](https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/)

and 

[Error Handling in Connect](https://cwiki.apache.org/confluence/display/KAFKA/KIP-298%3A+Error+Handling+in+Connect)

and 

[Error tolerance in Connect](https://www.javierholguera.com/2020/04/13/error-tolerance-in-kafka-connect-i/)

**Comment by kev-ms** [comment]
Kafka has default behavior of failing the connector if any error noticed. Errors that connector identifies (eg. Invalid json format) can be handled explicitly by setting below connector properties to skip corrupt message.  
`Error Tolerance = all`
`Dead Letter Queue = <sink-dead-topic>`

Setting these properties will process valid messages as normal but route invalid messages(which connector can not process) to dead letter Kafka topic without failing connector.

These configurations apply only to errors during converting messages in connector and does not handle errors thrown from cosmosDB after successful conversion(eg. missing id in document)

Ref Docs: 
https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/
https://stackoverflow.com/questions/55175547/kafka-connect-jdbc-sink-sql-exception/55178381#55178381

**Comment by ryancrawcour** [comment]
got it. but, once the connector is in a failed state is it expected behavior to have to completely delete, and reconfigure it. or should you be able to restart it and get it out of a failed state?

**Comment by sivamu** [comment]
There's a way to restart the connector and the tasks through the REST API,
```
curl -X POST localhost:8083/connectors/<connector-name>/restart
curl -X POST localhost:8083/connectors/<connector-name>/tasks/0/restart
```
but couldn't find any way to do this through the Control Center.

**Comment by kev-ms** [comment]
If the error can be remediated (eg. bad DB name, invalid master key), we should be able to reconfigure and restart without deleting them. 
But if it can not be remediated (eg. valid JSON with no id key) and bad data is still in Kafka topic it can not be restarted since connector will try to pick conversion where it left off and it will go back to failed state.

**Comment by ryancrawcour** [comment]
ok, so i am closing this issue then. we just need to make sure in our code that we handle errors appropriately so that the built-in dead-lettering capabilities are used for some exceptions where it makes sense (like invalid json on a message).
