### ISSUE TITLE
Sink connector needs to be able to support Converters

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#193]
Sink connector needs to be able to support Converters so that we can support JSON (string without a schema) as we do today, but also JSON with a schema, and AVRO. 

Add a test to ensure that when the connector is configured with avro and json-schema converters it works as expected.

**Comment by sivamu** [comment]
Unassigning myself from this issue for now. This requires the struct to json conversion, which will be very similar to the json to struct conversion taking place in #194.
