### ISSUE TITLE
Report CSE feedback for SDK issue

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#196]
Need to file feedback in CSE project for https://github.com/microsoft/kafka-connect-cosmosdb/issues/46
issue reporting is https://github.com/Azure/azure-sdk-for-java/issues/18091

**Comment by sivamu** [comment]
Created the following CSE feedback item
https://csefy19.visualstudio.com/CSEng/_workitems/edit/414040/
