### ISSUE TITLE
Refactor config logic for both connectors

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#199]
Refactor our config logic to match the approach taken by the [JDBC connector](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java). 

This approach allows for much greater flexibility when it comes to setting the various properties of each config item in ConfigDef. 
Our existing approach is too generic and makes it hard to set specific settings on config items. 
It defaults things to Importance of MEDIUM, when items should be HIGH
It defaults types to STRING or LONG etc. and makes it really difficult to configure datatypes properly. 

Getting this config def stuff right is important because this drives what the user's see when they go to configure our connectors. 

We should take lead from the verification checklist around config and ensure all our config items adhere to these points below.

Connectors should properly and completely define a ConfigDef to include all configuration items, including documentation and default values, organized into meaningful groups. We also follow some best practices for designing the configuration properties for a connector, including:

1. Expose the fewest configuration properties required to configure a connector, keeping it as simple as possible but not too simple. 
2. Always define a short, human readable display name in title case (e.g., “Database Name”). 
3. Always define a meaningful, human readable documentation string that is short enough but also complete enough for most users to understand what the configuration does. 
4. Always use the appropriate and restrictive type for the configuration property (e.g., “int”, “string”, “double”, “list”, etc.). Always use “PASSWORD” type for secrets and credentials. (Some property values, like JDBC URLs, can contain passwords or secrets. In this case, it’s better if the different segments within JDBC URL were represented as separate configuration properties. This doesn’t always work.) 
5. Provide a validator for most configuration properties to provide the user immediate feedback when creating a configuration. Ideally, a connector whose configuration validates will always run, barring any transient problems communicating with the backend. Where possible, the value of a configuration property should not be case-sensitive (e.g., “avro” and “Avro” and “AVRO” might all be valid). 
6. Provide a recommender when the configuration property has a limited number of choices for values. Always provide a recommender for enumerated literals. The recommender can communicate with the external service, but be careful that this never takes more than a few seconds, since this may block the connector and the Connect worker thread. 
7. Use dependencies between configuration properties to dynamically “show” or “hide” configuration properties based upon the value of another configuration property. For example, consider a connector property “mode” that can be set to either “default” or “exact”, and another property “mode.exact.range” should apply only for the “exact” mode. In this case, the “mode.exact.range” can be dependent upon the “mode” property, such that “mode.exact.range” is hidden when “mode=default” and unhidden when “mode=exact”. This is used in Control Center and other tools driven entirely by ConfigDef. 
8. Use appropriate importance, which generally correspond to: 
a. HIGH for configuration properties that are important enough to always consider, 
b. MEDIUM for configuration properties that have defaults that are somewhat advanced, and whose defaults should be acceptable for users who aren’t sure what to pick, and 
c. LOW for configuration properties that have defaults and are typically needed in advanced cases. 
9. Use defaults wherever possible, especially on MEDIUM and LOW importance properties. 
10. Organize related configuration properties into groups, with human-readable group names. Specify the order of properties within each group, starting with those properties that have a HIGH importance, then MEDIUM, then LOW importance. 

We consider configuration and ConfigDefs as public APIs, so it’s critical that we maintain backward compatibility when releasing new versions. Any configuration created by a customer for an older version should work with all newer versions of the connector, with no changes. Yes, the user might want to edit their configuration to utilize more recently-added configurations, and it’s possible some configurations were deprecated and any of these in the user’s connector configuration might not be used in newer versions of the connector. Some configurations can even be removed (preferably after a deprecation process) once the connector no longer uses them to control behavior._

**Comment by sivamu** [comment]
Before I forget, be sure to set a dependency between the Message_key_Field and message_key_enabled settings.
