### ISSUE TITLE
Rework integration tests, add guide to run them

### ISSUE THREAD

**Issue by sivamu** [microsoft/kafka-connect-cosmosdb#205]
While we have integration tests in this repo, there isn't a way to run them. Figure out a way to do this through maven or perhaps through VSCode, and write up a mini Readme explaining how to run these tests.

Add integration test for Sink TTL, auto ID gen

**Comment by ryancrawcour** [comment]
thanks. perhaps put the guide in the Developer walkthrough docs we've got already.

**Comment by ryancrawcour** [comment]
also, these integration tests need to be callable from within our release workflow. there it might just be as simple as invoking the main method of the jar file. not sure. but worth documenting this too.
