### ISSUE TITLE
Address issues observed by verification team

### ISSUE THREAD

**Issue by sivamu** [microsoft/kafka-connect-cosmosdb#224]
The Kafka connect verification team returned with an email this morning about some issues they have observed with our connectors. Most of them should be handled by some existing issues but there are some that need to be looked into.

### Pending
N/A

### Addressed
- We had to modify the docker compose file to run the connector in Standalone mode, Distributed mode and for Avro convertor (issue created in #231)
- Packaging is not logical as it is producing a fat jar including all the connector jars and the dependencies. We believe this can be resolved using a different package plug-in. (addressed by #202)
- SMT is not supported as the records are not in a proper Avro or JSON format. (addressed by #193 and #194)
- The connector do not implement Avro and JSON convertor properly as all the records fields are converted into one single record in string format. (addressed by #193 and #194)
- Connector do not support Exactly once delivery as the connector is unable to process records that have been added prior to running the connector or while being offline. Also sometimes it produced duplicate records in the kafka. (issue created in #232, possible overlap with #166)
- When trying to run the connector locally in a linux machine we were getting the following error (issue created #233)

**Comment by brandynbrown** [comment]
All items accounted for via other tickets.
