### ISSUE TITLE
SPIKE: Test Sink Connector with Map & Byte Data types

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#238]
Add observations for Sink Connector behavior using below converters when Kafka topic contains data in Byte and Map Format.
1. JSON converter with schema enabled
2. AVRO converter

Create issues to implement necessary fix to support these data types with cosmos db sink connector.

**Comment by brandynbrown** [comment]
@kev-ms can you add a deliverable/description please: ) Also this is M2 as well, yes?

**Comment by ryancrawcour** [comment]
work was completed on this. connector handles Map type, and does not handle Byte type. 
documented as such. 
a future enhancement to handle additional types can be considered, but this specific Spike is now closed.
