### ISSUE TITLE
Build must fail when warnings arise

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#242]
When testing yields warnings, we should fail the build.

Build should fail on linter issues in Java code. Ryan mentioned that the following maven plugin can help with this:
```    
  <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.6.0</version>
    <executions>
      <execution>
        <id>compile</id>
        <phase>process-sources</phase>
        <goals>
          <goal>compile</goal>
        </goals>
        <configuration>
          <compilerArgument>-Xlint:-processing</compilerArgument>
          <failOnWarning>true</failOnWarning>
        </configuration>
      </execution>
    </executions>
  </plugin>
```

**Comment by kev-ms** [comment]
[SonarQube](https://www.sonarqube.org/github-integration/?gads_campaign=SonarQube-US&gads_ad_group=SQ-GitHub&gads_keyword=sonar%20github&gclid=EAIaIQobChMIy4yKppq47gIVTfDACh0m2QHrEAAYASAAEgJZZ_D_BwE) provides static analysis of code as per requirement (equivalent to sonarlint vscode extension)but to decorate them with PRs and CI pipelines, project requires developer edition or above.
