### ISSUE TITLE
Update ids and names

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#246]
Update the following - 
groupId - com.azure.cosmos.kafka
artifactId - kafka-connect-cosmos
version - 1.0-beta
name - kafka-connect-cosmos

New Updated as Per Confluent:

- <title>Azure CosmosDB Source Connector</title>
-  <service-name> Connector (Source and Sink). i.e. Azure CosmosDB Connector.

**Comment by kev-ms** [comment]
New Updated as Per Confluent:

- <title>Azure CosmosDB Source Connector</title>
- Connector (Source and Sink). i.e. Azure CosmosDB Connector.
