### ISSUE TITLE
Run test suite for verification metrics

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#251]
Implementation of #314 

### Actions for this ticket:
- [ ] Reset/Reconfigure workers
- [ ] "Mark" monitoring for start of test
- [ ] Run automated client ramp
        - Warm Up
        - Steady State
        - Cool Down
- [ ] "Mark" monitoring for end of test

#### Notes:
- Number of Topics - 1
- Number of Topic partitions per topic - throughput / 1000
- Number of Tasks - 1 / partition

**Comment by brandynbrown** [comment]
@ryancrawcour do we have the previous numbers as well? It might be good to put this info in the GP.

**Comment by jkeane** [comment]
Is there any guidance on the size of each worker?  Have we done any kind of napkin estimate for how big CosmosDB would need to be scaled to satisfy that performance?

This infrastructure would be good to keep around to help with burn-in testing as well as helping to satisfy any exit criteria for release such as "sustained load for X days, < Y% errors in logs"

**Comment by sivamu** [comment]
I am not aware of any additional details given besides these numbers. As for the size of the workers, I'm using the CPU request limit K8S definition to parameterize how large each worker will be.
I've been using the [Cosmos capacity calculator](https://cosmos.azure.com/capacitycalculator/) for getting rough estimates and having solely 3000 creates/sec results in about 15k RU/s, which is quite steep. I'll look into a way to perhaps work around this.

Yup, agree with the last part, having something similar to our previous projects for long running tests should give us some valuable data.

**Comment by jkeane** [comment]
Pending the guidance from Confluent, lets assume the 3000/sec number is a sustained number for >= 10m.
