### ISSUE TITLE
Source connector error when Cosmos collection is empty

### ISSUE THREAD

**Issue by sivamu** [microsoft/kafka-connect-cosmosdb#267]
From the latest verification run by the Confluent Team:

The source connector is throwing an unknown error when the collection is empty.
It is breaking the Kafka-connect service.

<img width="493" alt="empty-error" src="https://user-images.githubusercontent.com/12498689/105750422-5d074000-5f0a-11eb-9abb-00b850acf1e2.PNG">

**Comment by kev-ms** [comment]
Current release doesn't have standalone support that was added as part of #268. Validating standalone mode with dev jar resolves the issue. Team will push new release to unblock verification team from this bug.
