### ISSUE TITLE
Guided code review with Cosmos DB leads

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#275]
- [ ] What are the main points to cover?
- [ ] Who will lead this?
- [ ] Set the meeting

**Comment by brandynbrown** [comment]
@ryancrawcour @jkeane please schedule a meeting for this and include the team.

**Comment by ryancrawcour** [comment]
done

**Comment by brandynbrown** [comment]
@jkeane this was scheduled and has since been cancelled so I am not sure where this sits, but must still be done/accounted for.

**Comment by brandynbrown** [comment]
meeting rescheduled for 2/25
