### ISSUE TITLE
Spike: Topic Mapping Solution Investigation

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#292]
**## Problem Statement**
Please see #83 

**## What**
- [ ] Investigate whether it's feasible to configure a worker to a specific topic
    - [ ] If so, are there performance improvements?
- [ ] Investigate what Cassandra connector does when monitoring multiple topics

**## Deliver**
- [ ] Please note your findings in ticket #83 and add Design Review label
- [ ] Remove the blocked label

## Next Steps

- [ ] Team consensus to proceed
- [ ] Schedule Design Session
- [ ] Complete Design Review

**Comment by ryancrawcour** [comment]
closing this issue as it's an extension of #83 
will just track that issue in one place to avoid duplication
