### ISSUE TITLE
Observability Accountability - Scheduled for 2/9

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#297]
As a team, we should all know the answers to the following questions:
- [ ] What have we done to account for observability?
- [ ] How will we communicate our approach and implementations regarding observability?

**Comment by brandynbrown** [comment]
This is actually covered in the EF checklist so maybe that would be the best place to start -- this is a random note: )

**Comment by ryancrawcour** [comment]
observability for a component that you install in to a platform, like Kafka Connect, is somewhat limited. 
we haven't built any custom dashboards as there is no need
we have surfaced logs from the connectors as appropriate for Kafka Connect to make available. 

i am satisfied with the observability as it stands today.
