### ISSUE TITLE
Duplicate messages are created in Kafka Topic

### ISSUE THREAD

**Issue by kev-ms** [microsoft/kafka-connect-cosmosdb#304]
Here is the recorded steps: 
https://confluent.zoom.us/rec/share/hRKNPZcBQ9ElxDTa4za8j71rrcM3jjqGLtYAGfQxBG7MPTOElMa4FCmAPmApn8Ga.LkcV48P2ekK0D7HY

**Comment by sivamu** [comment]
Unable to reproduce this bug, had a call with Rankesh for a live-debug session and we weren't able to repro the bug then as well. 

Will try it again through the Confluent standalone utility to see if that makes a difference since this was what Rankesh tried with at first.
