### ISSUE TITLE
Boolean default values don't show up properly Control-center

### ISSUE THREAD

**Issue by sivamu** [microsoft/kafka-connect-cosmosdb#307]
## Description
The boolean default config values show up as "true" even when "false" is specified as a default.

![image](https://user-images.githubusercontent.com/67930841/106658879-8146ca80-6563-11eb-93d6-932a07e18724.png)

**Comment by kev-ms** [comment]
This bug seems to be on kafka config class. Observed similar behavior in other connectors' config as well as default error configs with `Boolean` type. 

Possible workaround could be configuring field as String instead of Boolean, that would convert config dropdown to free text box.

**Comment by brandynbrown** [comment]
@kev-ms to your point, that would kind of defeat the purpose. I am going to put this in the handoff epic to be discussed with the PG.

**Comment by ryancrawcour** [comment]
Sounds like a bug on Kafka side.  Not cosmos side.

________________________________

**Comment by ryancrawcour** [comment]
They did say somewhere in their docs to not use boolean but instead use an array of supported values ... In our case yes/no or true/false or "enabled/disabled"

Can't remember where in the docs it gives an example of this. Perhaps in the Checklist doc linked in the project?
________________________________

**Comment by brandynbrown** [comment]
@kev-ms should we explore Ryan's suggestion in M2?

**Comment by kev-ms** [comment]
Yes, we should look in to those alternatives

**Comment by brandynbrown** [comment]
The consensus was to fix this by not using booleans as that is what's noted in the docs.
