### ISSUE TITLE
Balance changefeed among multiple source workers

### ISSUE THREAD

**Issue by sivamu** [microsoft/kafka-connect-cosmosdb#309]
Currently, spinning up multiple source tasks results in duplicate entries in Kafka since each task's change feed processor is reading the Cosmos changes individually. We would need them to share the workload of reading changes so that we can scale the source connectors.

Here's some advice from Milis from the PG on how to approach this:
>    https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/ChangeFeedProcessorOptions.java#L155
>    this allows you to set a shared lease ID across multiple instances
>    you will still need a unique "hostName" for each instance: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/ChangeFeedProcessorBuilder.java#L37
>    if multiple instances share the same lease prefix, the work to process the changes will be load balanced between all the instances
>    the current workload is load balanced based on the number of physical partitions and you might need to keep that in mind as to how many CFP instance you will like to run

**Comment by ryancrawcour** [comment]
Good point.

This is why we should be testing with at least 2 workers. Each worker gets a distinct name but shares the same lease collection and then their change feed processor takes care of balancing.

We'll have to think about how to handle the number of partitions vs the number of workers. Might need advice from PG here.

________________________________
