### ISSUE TITLE
SPIKE: Performance testing plan to meet metrics

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#314]
In order to gain gold verification, we need to fill out the following chart.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12498689/106937236-25a34b00-66e3-11eb-8eeb-25258654fcd9.png)

Original Notes from Jim:
<img width="461" alt="jims-notes-perf" src="https://user-images.githubusercontent.com/12498689/106938945-394fb100-66e5-11eb-9ece-f817d0f19552.PNG">

### Outstanding Questions:
- [x] How to monitor Kafka queue? @kev-ms 
- [x] How to export data from Grafana for steady state? @kev-ms 
- [x] Align ticketing to design plan @brandynbrown 
- [x] Rate for Cosmos DB change feed processor @sivamu 
- [x] How are we creating load in Cosmos? @kev-ms 
- [x] What is Kafka guidance on number of topics and partitions / topic? @sivamu 
- [x] How to run multiple clients? @sivamu 
- [x] Scale down worker harness - multiple workers on same compute unit @sivamu

**Comment by sivamu** [comment]
Guidance for the choosing the number of topics/partitions: 
https://www.confluent.io/blog/how-choose-number-topics-partitions-kafka-cluster/

Long story short, if we can determine the max rate of messages/sec our sink/source connector processes at, we can determine the target number of partitions based on the desired throughput.

**Comment by kev-ms** [comment]
Reg. How to export data from Grafana for steady state?
Data-points can be exported from any panel by filtering data within steady state and navigating to `Inspect->Data->Download CSV`
https://grafana.com/docs/grafana/latest/panels/inspect-panel/

**Comment by kev-ms** [comment]
Create load in cosmosdb
-  Automate dataload using [Stored Procedure and Logic Apps](https://vincentlauzon.com/2017/10/19/invoking-a-stored-procedure-from-a-partitioned-cosmosdb-collection-from-logic-apps/)
- [Azure Bulk Executor Library](https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-java)

**Comment by ryancrawcour** [comment]
I wouldn't use stored procedures.

**Comment by kev-ms** [comment]
Agree. Bulk executor should mostly fulfill our needs here.

**Comment by brandynbrown** [comment]
@jkeane @kev-ms are we good on this ticket? Can we close?

**Comment by kev-ms** [comment]
I am good with that. 
There are couple ways to derive kafka queue using helm charts of `kafka minion` or `lag exporter`
