### ISSUE TITLE
Research Cosmos Setup for Performance Testing

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#317]
Results of spike enable implementation of #251 

See if we can use the Cosmos DB emulator for performance tests, rather than an actual Cosmos DB instance. The RUs needed for a scaled Cosmos DB instance can be substantial and can get expensive, hence this spike.

**Comment by sivamu** [comment]
Closing out this since we don't want to use the emulator for the actual performance tests.
