### ISSUE TITLE
Update Repo Maintainer

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#331]
For some reason, I cannot add people to our groups with access so you will have to do this - TY

- [x] Update maintainer (confirm who with PG or change to Jim Keane until handoff complete)

**Comment by ryancrawcour** [comment]
maintainer is set as agreed with PG. it is currently assigned to a github team, that way it's not a single person, and the PG can add anyone they like in to this team.
