### ISSUE TITLE
Add a config property to append a string to the user agent.

### ISSUE THREAD

**Issue by NathanNam** [microsoft/kafka-connect-cosmosdb#376]
**## Problem Statement**
To determine whether connections and records are coming from Confluent Cloud, we will need to append a string to the user agent.

**## Proposed Solution**
It could be a config property called "provider" with null by default.

## Next Steps

- [ ] Team consensus to proceed
- [ ] Schedule Design Session
- [ ] Complete Design Review

**Comment by ryancrawcour** [comment]
how do you create a config property that is hidden from the user?

**Comment by NathanNam** [comment]
I should have been clear. I think the property can be visible to users. In Confluent Cloud, we can set it to a certain value and hide this property from users.

**Comment by ryancrawcour** [comment]
got it. i will add this new property today.

**Comment by NathanNam** [comment]
@ryancrawcour is this issue resolved?

**Comment by ryancrawcour** [comment]
> @ryancrawcour is this issue resolved?

sorry, not yet. i have been a bit slammed lately. is this holding you up?

**Comment by NathanNam** [comment]
We'd like to have this one available before we put the connector in GA for Confluent Cloud.

**Comment by ryancrawcour** [comment]
would happily accept a PR for this 😂
else, i can probably add it before the end of the week

**Comment by ryancrawcour** [comment]
@NathanNam there's a PR for this. please take a look and let me know on that PR if it covers what you were looking for.
