### ISSUE TITLE
Remove support for INSERT mode

### ISSUE THREAD

**Issue by ncliang** [microsoft/kafka-connect-cosmosdb#381]
**## Problem Statement**
Since the connector does not implement `precommit` hook to allow for finer grained offset tracking within the batch, connect framework retries the entire batch of records when a single record in batch fails. This is fine if the connector is running in UPSERT mode, but problematic if in INSERT mode and some records in the batch have succeeded before a failure.

**## Proposed Solution**
Remove support for INSERT mode from the connector code, configs, and documentation.

**## Alternative Solutions**
- Implement `precommit` hook on the connector task to support for incrementing the offset at record granularity and allow for retries starting from just the failed record

**## Additional context**
https://kafka.apache.org/11/javadoc/org/apache/kafka/connect/sink/SinkTask.html#preCommit-java.util.Map-

## Next Steps

- [x] Team consensus to proceed
- [ ] Schedule Design Session
- [ ] Complete Design Review

**Comment by ryancrawcour** [comment]
should we not be implement precommit hook instead of removing this functionality? i am a mindful of the possible perf implications of always doing upsert ...

@kushagraThapar thoughts?

**Comment by ryancrawcour** [comment]
also, when a single record in a batch fails, should we be failing the entire batch? should we not be moving those failed messages to DLQ and continuing?

**Comment by ncliang** [comment]
@ryancrawcour good points about the precommit hook and DLQ support. I'll address them below.

DLQ support: we have added this support for sink connectors in https://issues.apache.org/jira/browse/KAFKA-9971 . To make use of this feature in a backwards-compatible manner, the connector can look for the new `ErrantRecordReporter` on the context and attempt to use it if found. We would not be able to use the DLQ in the `put()` method on Kafka versions pre-2.6 that do not have this feature. 
https://github.com/confluentinc/kafka-connect-jdbc/blob/c0252c3adb9e73bdbb3449e03b7cfc3057da8d77/src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java#L53

Implementing the precommit hook: the implementation in the connector would be quite simple since the client does a single write at a time with no batching. However, the connector would still fail and require user intervention when a record write fails. It makes things better in that when the connector fails and you attempt to restart it, you aren't re-delivering messages in the batch that have already been successfully delivered.

Given that users on Kafka < 2.6 would not get DLQ support, I think we would need to implement both to be able to support INSERT mode safely for users on Kafka < 2.6 . My understanding from @kushagraThapar and @moderakh before was that there are other cosmos clients that have supported UPSERT only for now and we were comfortable moving forward with this in the short term while we continue to improve INSERT support.
