### ISSUE TITLE
Must be able to use ChangeFeed to replay data in source

### ISSUE THREAD

**Issue by ryancrawcour** [Microsoft/kafka-connect-cosmosdb#4]
For source (where Cosmos DB is the source), use the ChangeFeed to replay the data

**Comment by ryancrawcour** [comment]
@skarri-microsoft & @arramac  do you think we need all 3 for P0, or just ChangeFeed, and add the others later?

**Comment by arramac** [comment]
I think only Change feed is P0. Read Feed is redundant since change feed can support read from beginning, which is change feed. Query is really a workaround because we don't have filtered change feed, I'd like to leave it out unless early adopters (Walmart) absolutely need it

**Comment by ryancrawcour** [comment]
I'll add a "nice to have" (P2) for query support.
