### ISSUE TITLE
Cosmos Gremlin API as source

### ISSUE THREAD

**Issue by dArignac** [microsoft/kafka-connect-cosmosdb#412]
**## Problem Statement**
I tested the connector and the sink connector works with Gremlin API as well. I tried setting up the source connector using a Gremlin API, but it fails as it seems that the partition key is automatically set to `/id`, which is disallowed in Gremlin API: `Partition key path /id is invalid for Gremlin API. The path cannot be '/id', '/label' or a nested path such as '/key/path'`

**## Proposed Solution**
Add support for using Gremlin API as source and provide an option for specifying the partition key of the used graph.

**## Alternative Solutions**
Did not investigate anything else.

**## Additional context**
Was only able to create the source connector using an Cosmos DB account which is not serverless, creating the source connector with a serverless account stated `Setting offer throughput or autopilot on container is not supported for serverless accounts`.

Source connector config 

```
{
	"name": "cosmosdb-source-connector",
	"config": {
		"connector.class": "com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector",
		"tasks.max": "1",
		"key.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"connect.cosmos.task.poll.interval": "100",
		"connect.cosmos.connection.endpoint": "https://<XXX>.documents.azure.com:443/",
		"connect.cosmos.master.key": "secretkey",
		"connect.cosmos.databasename": "testdb",
		"connect.cosmos.containers.topicmap": "demo1#graph1",
		"connect.cosmos.offset.useLatest": false,
		"value.converter.schemas.enable": "false",
		"key.converter.schemas.enable": "false"
	}
}
```

## Next Steps

- [ ] Team consensus to proceed
- [ ] Schedule Design Session
- [ ] Complete Design Review

**Comment by ryancrawcour** [comment]
@dArignac did you ever try the above linked connector for the Gremlin API? 

closing this issue, if you wish to reopen it please do so.
