### ISSUE TITLE
Failed to find any class that implements Connector when using JDK 1.8

### ISSUE THREAD

**Issue by vdesabou** [microsoft/kafka-connect-cosmosdb#413]
## Description

When trying to deploy Sink or Source connector with Confluent Platform `5.5.5` (which is using OpenJDK 1.8) , I'm getting:

```
{
"error_code": 500,
"message": "Failed to find any class that implements Connector and which name matches com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='5.5.5-ce', encodedVersion=5.5.5-ce, type=source, typeName='source', location='classpath'}"
2021-08-29T20:28:38.7758346Z }
```

whereas **exactly** the same test using CP 6.x (with OpenJDK 11) is working fine.
I did not see anywhere in the documentation that JDK 1.8 is not supported.

## Expected Behavior

Connector can be used with JDK 1.8

## Reproduce

1. Follow instructions from https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-azure-cosmosdb-source
2. export TAG=5.5.5
3. execute script `azure-cosmosdb-source.sh`
4. See error in connect logs `docker container logs connect`

## Additional Context

See issue https://github.com/vdesabou/kafka-docker-playground/issues/1230 with some links to the tests with different versions

**Comment by motonisar** [comment]
I am getting the same issue when using java 8 , was it resolved?
I am running:
confluent-hub install microsoftcorporation/kafka-connect-cosmos:1.2.4 with openjdk 8 

I tried running java 11 and the connect service itself crashes.

Could you please help with the possible solution?
@vdesabou 

logs:
Jan 12 15:43:45 ubtu-az-np-0031 connect-distributed[19767]: [2022-01-12 15:43:45,508] ERROR Failed to start task interactions-cosmosdb-source-connector-0 (org.apache.kafka.connect.runtime.Worker:574)
Jan 12 15:43:45 ubtu-az-np-0031 connect-distributed[19767]: org.apache.kafka.common.config.ConfigException: Invalid value com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask for configuration task.class: Class com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask could not be found.

**Comment by vdesabou** [comment]
@motonisar No it has never been fixed

Check out a working example there https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-azure-cosmosdb-source I'm not sure what `task.class` is..
It should be `"connector.class": "com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector"` IMHO

**Comment by motonisar** [comment]
@vdesabou - When I run the connector its not able to find com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector on  jdk1.8. The previous message was from logs. I am specifying the connector.class , please find my connector config in use

 {
  "name": "test-cosmos",
  "config": {
    "connector.class": "com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "connect.cosmos.task.poll.interval": "100",
    "connect.cosmos.connection.endpoint": "https://documents.azure.com:443/",
    "connect.cosmos.master.key": "REDACTED",
    "connect.cosmos.databasename": "test-db",
    "connect.cosmos.containers.topicmap": "test-interactions#interactions",
    "connect.cosmos.offset.useLatest": false,
    "value.converter.schemas.enable": "false",
    "key.converter.schemas.enable": "false",
    "confluent.topic.bootstrap.servers": "broker:9092",
    "confluent.topic.replication.factor":"1",
    "confluent.topic.security.protocol":"SASL_SSL",
    "confluent.topic.sasl.mechanism":"PLAIN",
    "confluent.topic.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"REDACTED\" password=\"REDACTED\";" 
  }
}

Error:
{
    "error_code": 500,
    "message": "Failed to find any class that implements Connector and which name matches com.azure.cosmos.kafka.connect.source.CosmosDBSourceConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector,
