### ISSUE TITLE
How to use this as Sink Connector

### ISSUE THREAD

**Issue by akash66** [microsoft/kafka-connect-cosmosdb#94]
Hi,

I would like to know how to use _kafka-connect-cosmosdb_ as Sink Connector. I don't see it on Confluent Hub. It would be very helpful knowing how to use this since I am trying to Sink data from Kafka Topic to CosmosDB.

**Comment by ryancrawcour** [comment]
It has not yet been published on Confluent Hub. However, you can still build the jar file and use it in Kafka Connect.

**Comment by ryancrawcour** [comment]
What kind of data are you trying to Sink? Currently the connector only supports JSON data. Avro support is on the backlog.

**Comment by akash66** [comment]
I am trying to sink JSON data into Cosmos DB. I followed the below steps
but wasn't able to see the Cosmos DB Connector. Please let me know if I
am missing something.

1. Built the *kafka-connect-cosmosdb-master* using *sbt compile and sbt
package* command. This generated a jar file,
*kafka-connect-cosmosdb-master/target/scala-2.12**/*
*com-microsoft-azure-cosmosdb-kafka-connect_2.12-0.0.1-preview.jar*.
2. Copied the above jar inside a custom folder named
custom-cosmosdb-sink-connector on my local.
3. I am mounting this custom folder to relevant path in Landoop Docker
Image. I am using landoop docker image to run the kafka cluster. I have
attached a screenshot of my docker-compose file.
4. Post this I ran my docker-compose and brought up the container hosting
Landoop connectors UI. I have attached the Landoop UI where I don't find
the Cosmos DB Connector.

Please help me out with this.

Thanks,
Akash

**Comment by akash66** [comment]
Hi Ryan,

I hope I was able to convey the issue which I am facing with the deployment
of Kafka-CosmosDB-Connector. Please let me know if I am doing
something wrong.

Thanks,
Akash

**Comment by ryancrawcour** [comment]
Can you please share your Connect config for this connector. Thanks.

**Comment by ryancrawcour** [comment]
created #97 to address this question

**Comment by akash66** [comment]
Hi Ryan,

Is it fine if I share the Connect config now?

Regards,
Akash

**Comment by ryancrawcour** [comment]
Sure. Happy to take a look if you share it.

**Comment by ryancrawcour** [comment]
Also, we've done a large rebuild of this connector with Java and the new Cosmos DB SDKs etc. so please be sure to test the version found in the dev branch (not the old Scala one). Thanks.

**Comment by akash66** [comment]
Aah okay, I saw the latest java edition of this connector. Cool. I will try
building this locally and use it. Will get back once done.

Thanks,
Akash
