### ISSUE TITLE
Confluent 3rd Party Connector Support Request

### ISSUE THREAD

**Issue by sbpkumar7** [microsoft/kafka-connect-cosmosdb#96]
Hi Team,

Since this is a Microsoft open-source Connector is it possible for you to initiate the process to work with the Confluent partner program team to provide the connector to Confluent for verification. Once verified, it would be listed on Confluent Hub and can we get the required support from Microsoft for any issues, bugs?

**Comment by ryancrawcour** [comment]
that process is currently underway. 

you can raise any issues / bugs for this here, on this repo.
you can contribute new updates / fixes / and features here on this repo, in accordance with the contribution guidelines listed on the repo. 

you cannot raise a Microsoft support ticket for this particular component

**Comment by ryancrawcour** [comment]
this is a requirement for #1
